# Generated by Django 5.1.2 on 2024-10-29 19:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "social_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("address", models.CharField(max_length=200)),
                ("occupation", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
